### ISSUE TITLE
thermistor table values

### ISSUE THREAD

**Issue by hurzl** [bkubicek/Marlin#24]
what are the "*16"s in thermistortables.h for? I have a 100k thermistor and the values are only correct when I take the 16s out.

**Comment by bkubicek** [comment]
i have asked the guy who designed the first thermistor table ever, and he does not know.
you need to ask zalm, maybe he knows

**Comment by bkubicek** [comment]
I had actually the same problem, for a reprap with a 10k thermistor. Its not in sprinter, i think zalm actually changed it. Should i use the thermistor tables of sptrinter instead?

**Comment by bkubicek** [comment]
i know the reason, and know how to fix it.

**Comment by hurzl** [comment]
delete the "*16" fixed it for me.
I just would like  to have it in the repo, so I don't have to fix it every time ;-)

**Comment by bkubicek** [comment]
I made it configurable.  The magic 16 was the number of temperature measurements that were added, before they were translated to temperature.Oversampling basically for additional numerical accuracy.  I rewrote the temperature code to be useful for the AD595 chip, and took the code from sprinter where no oversampling occurs. That was the reason for the failure.
However, I am not really for that concept, because if you would use PID, the "I" would actually do some averaging already, as far as I understand.
